export const GET_CATEGORY='GET_CATEGORY';
export const GET_ALL_PRODUCT='GET_ALL_PRODUCT';
export const ADD_TOCARD='ADD_TOCARD';
export const DELETE_TO_CARD='DELETE_TO_CARD'
export const SEARCH_DATA='SEARCH_DATA'
export const PRODUCTS_DATA='PRODUCTS_DATA'
